var scuoleData = [{
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DOMENICO SAVIO PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "DIREZIONE DIDATTICA 5o CIRCOLO",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GIAN PAOLO COSTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "DIREZIONE DIDATTICA 5o CIRCOLO",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GRAZIA DELEDDA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "DIREZIONE DIDATTICA 5o CIRCOLO",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "JEAN PIAGET",
	"Tipo struttura": "Statale",
	"Istituzione scol": "DIREZIONE DIDATTICA 5o CIRCOLO",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "PIERO BERTOLINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "DIREZIONE DIDATTICA 5o CIRCOLO",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "COLLEGIO S.LUIGI",
	"Tipo struttura": "Privata convenzionata",
	"Istituzione scol": "ISTITUTO COLLEGIO SAN LUIGI",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "COLLEGIO S.LUIGI",
	"Tipo struttura": "Privata paritaria",
	"Istituzione scol": "ISTITUTO COLLEGIO SAN LUIGI",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "COLLEGIO S.LUIGI",
	"Tipo struttura": "Privata paritaria",
	"Istituzione scol": "ISTITUTO COLLEGIO SAN LUIGI",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA SECONDARIA DI SECONDO GRADO",
	"Struttura": "COLLEGIO S.LUIGI",
	"Tipo struttura": "Privata paritaria",
	"Istituzione scol": "ISTITUTO COLLEGIO SAN LUIGI",
	"indirizzo": "",
	"lon": "",
	"lat": "",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CASA O.\"P.SICILIANI\"  (CTP DOZZA)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA DEL PRATELLO,34",
	"lon": "11.33379081",
	"lat": "44.49550196",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CESANA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA ALESSANDRO GUARDASSONI,1",
	"lon": "11.29893287",
	"lat": "44.49295264",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GIORGIO MORANDI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA DEL BECCACCINO,27",
	"lon": "11.29175331",
	"lat": "44.49312353",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GIOVANNI XXIII",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA ADOLFO DE CAROLIS",
	"lon": "11.29901212",
	"lat": "44.49970475",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GIOVANNI XXIII PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA LEONARDO DA VINCI,3",
	"lon": "11.28553033",
	"lat": "44.49740532",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "GIUSEPPE DOZZA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA ADOLFO DE CAROLIS,23",
	"lon": "11.29900804",
	"lat": "44.4991817",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "ISTITUTO PENALE PER MINORENNI (CTP DOZZA) ",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 1",
	"indirizzo": "VIA DEL PRATELLO,34",
	"lon": "11.33379081",
	"lat": "44.49550196",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "BESTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIALE ALDO MORO,31",
	"lon": "11.36266206",
	"lat": "44.5083959",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CASA CIRCONDARIALE DOZZA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA DEL GOMITO,4",
	"lon": "11.36967019",
	"lat": "44.53484844",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "CASA CIRCONDARIALE DOZZA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA DEL GOMITO,4",
	"lon": "11.36967019",
	"lat": "44.53484844",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CHIOSTRI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA ATHOS BELLETTINI,7",
	"lon": "11.3600648",
	"lat": "44.50923283",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GIOANNETTI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA GIUSEPPE GIOANNETTI,2",
	"lon": "11.36494972",
	"lat": "44.5052031",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GUALANDI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA FILIPPO BEROALDO,2",
	"lon": "11.36598656",
	"lat": "44.50336961",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GUALANDI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA DELL'ARTIGIANO,5",
	"lon": "11.36633172",
	"lat": "44.5029993",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "IST.ORTOPEDICO RIZZOLI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 10",
	"indirizzo": "VIA GIULIO CESARE PUPILLI,2",
	"lon": "11.34192078",
	"lat": "44.48052128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "BENINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA FERRUCCIO BENINI,3",
	"lon": "11.37453955",
	"lat": "44.50360435",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DON MINZONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA VALPARAISO,2",
	"lon": "11.37946563",
	"lat": "44.50761093",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GARIBALDI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA ISABELLA ANDREINI,41",
	"lon": "11.3730712",
	"lat": "44.50022045",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GARIBALDI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA FILIPPO BEROALDO,34",
	"lon": "11.37228882",
	"lat": "44.50045322",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "PANZINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA ALFREDO PANZINI,5",
	"lon": "11.39357941",
	"lat": "44.50860567",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ROMAGNOLI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA ALFREDO PANZINI,3",
	"lon": "11.39319351",
	"lat": "44.50904353",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN DONATO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "SAFFI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 11",
	"indirizzo": "VIA ALFREDO PANZINI,1",
	"lon": "11.3919711",
	"lat": "44.51026809",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "FARINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 12",
	"indirizzo": "VIA POPULONIA,11",
	"lon": "11.38566858",
	"lat": "44.48832536",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "PADRE O. MARELLA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 12",
	"indirizzo": "VIA POPULONIA,7/2",
	"lon": "11.38524488",
	"lat": "44.48762176",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "PADRE O. MARELLA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 12",
	"indirizzo": "VIA POPULONIA,7/2",
	"lon": "11.38524488",
	"lat": "44.48762176",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "VISCARDI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 12",
	"indirizzo": "VIA LORENZO BARTOLINI,4",
	"lon": "11.38274889",
	"lat": "44.48186128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "VISCARDI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 12",
	"indirizzo": "VIA LORENZO BARTOLINI,4",
	"lon": "11.38274889",
	"lat": "44.48186128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "FERRARI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA TOSCANA,136",
	"lon": "11.37013157",
	"lat": "44.45797117",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "FERRARI STATALE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA BUON PASTORE",
	"lon": "11.3691018",
	"lat": "44.46001369",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "FERRARI SUCC.",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA CESARE PAVESE,15",
	"lon": "11.36047414",
	"lat": "44.45121802",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "LEONARDO DA VINCI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA BUON PASTORE",
	"lon": "11.3691018",
	"lat": "44.46001369",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "TAMBRONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA AUGUSTO MURRI,158",
	"lon": "11.36872531",
	"lat": "44.4741106",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "TAMBRONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 13",
	"indirizzo": "VIA AUGUSTO MURRI,158",
	"lon": "11.36872531",
	"lat": "44.4741106",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "2 AGOSTO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA GALEAZZA",
	"lon": "11.27555224",
	"lat": "44.5046988",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ALDO MORO PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA SANTORRE DI SANTAROSA,2",
	"lon": "11.29294454",
	"lat": "44.52019217",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "FIORINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA EMILIA PONENTE,311",
	"lon": "11.29024461",
	"lat": "44.51138711",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "LIPPARINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA MAURIZIO BUFALINI,16",
	"lon": "11.27474503",
	"lat": "44.52066128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "MAZZINI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA DOMENICO BIANCOLELLI",
	"lon": "11.27115212",
	"lat": "44.52305821",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "VOLTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA DOMENICO BIANCOLELLI",
	"lon": "11.27115212",
	"lat": "44.52305821",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "BORGO PANIGALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "VOLTA - SUCCURSALE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 14",
	"indirizzo": "VIA GALEAZZA,59",
	"lon": "11.277313",
	"lat": "44.5069404",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CASARALTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA ALFONSO LOMBARDI,40",
	"lon": "11.35169936",
	"lat": "44.51656568",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CROCE COPERTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA MARZIALE,12",
	"lon": "11.34927716",
	"lat": "44.53185422",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "DOZZA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA DELLA DOZZA,8",
	"lon": "11.36526464",
	"lat": "44.52946366",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DOZZA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA DELLA DOZZA,8",
	"lon": "11.36526464",
	"lat": "44.52946366",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "SUCC. SCUOLA DELL'INFANZIA STATALE DOZZA IL FLAUTO MAGICO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA ALFONSO LOMBARDI,42",
	"lon": "11.35221815",
	"lat": "44.5162318",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "SUCCURSALE CASARALTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA DI SALICETO,72",
	"lon": "11.3520477",
	"lat": "44.52305768",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "ZAPPA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 15",
	"indirizzo": "VIA DI SALICETO",
	"lon": "11.35023899",
	"lat": "44.51888821",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "DON BOSCO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "VIA POMPEO VIZZANI,56",
	"lon": "11.37074178",
	"lat": "44.49070064",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DON BOSCO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "VIA POMPEO VIZZANI,56",
	"lon": "11.37074178",
	"lat": "44.49070064",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "G.B. MARTINI (succ.G.RENI)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "PIAZZA ROSSINI",
	"lon": "11.34892926",
	"lat": "44.49542575",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "GUIDO RENI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "VICOLO BOLOGNETTI,10",
	"lon": "11.35417058",
	"lat": "44.49292603",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "MATTIUZZI CASALI (succ. DON BOSCO)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "VIA AZZURRA",
	"lon": "11.37356357",
	"lat": "44.48959403",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ZAMBONI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 16",
	"indirizzo": "VICOLO BOLOGNETTI",
	"lon": "11.3541258",
	"lat": "44.49321656",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "GANDINO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 17",
	"indirizzo": "VIA GRAZIANO,8",
	"lon": "11.33155678",
	"lat": "44.49995365",
	"nome": "Gandino",
	"tipo": "media",
	"stud": "431",
	"non_freq": "34",
	"stranieri": "76",
	"freq": "397"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GUIDI TERESINA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 17",
	"indirizzo": "VIA LUIGI CALORI,8",
	"lon": "11.330975",
	"lat": "44.5004044",
	"nome": "Guidi",
	"tipo": "infanzia",
	"stud": "76",
	"non_freq": "31",
	"stranieri": "23",
	"freq": "45"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GUIDI TERESINA PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 17",
	"indirizzo": "VIA LUIGI CALORI,8",
	"lon": "11.330975",
	"lat": "44.5004044",
	"nome": "Guidi",
	"tipo": "primaria",
	"stud": "342",
	"non_freq": "58",
	"stranieri": "75",
	"freq": "284"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "DE AMICIS",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 18",
	"indirizzo": "VIA MILAZZO,3/1",
	"lon": "11.34330565",
	"lat": "44.50320956",
	"nome": "De Amicis",
	"tipo": "infanzia",
	"stud": "70",
	"non_freq": "38",
	"stranieri": "",
	"freq": "32"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DE AMICIS",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 18",
	"indirizzo": "VIA MILAZZO,3/1",
	"lon": "11.34330565",
	"lat": "44.50320956",
	"nome": "De Amicis",
	"tipo": "primaria",
	"stud": "224",
	"non_freq": "74",
	"stranieri": "",
	"freq": "150"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "FABRIZIO DE ANDRE' ex Dante Alighieri",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 18",
	"indirizzo": "VIA ASIAGO,33",
	"lon": "11.31665238",
	"lat": "44.50028127",
	"nome": "De Andrè",
	"tipo": "media",
	"stud": "270",
	"non_freq": "85",
	"stranieri": "",
	"freq": "185"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "MONTERUMICI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 18",
	"indirizzo": "VIA ASIAGO,33",
	"lon": "11.31665238",
	"lat": "44.50028127",
	"nome": "Monterumici",
	"tipo": "primaria",
	"stud": "370",
	"non_freq": "78",
	"stranieri": "",
	"freq": "292"
}, {
	"Quartiere": "PORTO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "OSPEDALE MAGGIORE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 18",
	"indirizzo": "LARGO BARTOLO NIGRISOLI",
	"lon": "11.31577156",
	"lat": "44.50400561",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CREMONINI ONGARO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 19",
	"indirizzo": "VIA BELLOMBRA,28",
	"lon": "11.3386475",
	"lat": "44.48072152",
	"nome": "Cremonini",
	"tipo": "primaria",
	"stud": "287",
	"non_freq": "47",
	"stranieri": "23",
	"freq": "240"
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "IST.ORTOPEDICO RIZZOLI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 19",
	"indirizzo": "VIA GIULIO CESARE PUPILLI,2",
	"lon": "11.34192078",
	"lat": "44.48052128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "IST.ORTOPEDICO RIZZOLI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 19",
	"indirizzo": "VIA GIULIO CESARE PUPILLI,2",
	"lon": "11.34192078",
	"lat": "44.48052128",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "LAVINIA FONTANA (ex-CARDUCCI)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 19",
	"indirizzo": "VIA D'AZEGLIO,82",
	"lon": "11.33976493",
	"lat": "44.48756946",
	"nome": "Fontana",
	"tipo": "media",
	"stud": "238",
	"non_freq": "56",
	"stranieri": "",
	"freq": "182"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "LONGHENA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 19",
	"indirizzo": "VIA DI CASAGLIA,39",
	"lon": "11.30794225",
	"lat": "44.47786195",
	"nome": "Longhena",
	"tipo": "primaria",
	"stud": "368",
	"non_freq": "222",
	"stranieri": "4",
	"freq": "146"
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "ALBERTAZZI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 2",
	"indirizzo": "VIA BERRETTA ROSSA,15",
	"lon": "11.306438",
	"lat": "44.50444823",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ALBERTAZZI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 2",
	"indirizzo": "VIA BERRETTA ROSSA,15",
	"lon": "11.306438",
	"lat": "44.50444823",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DE VIGRI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 2",
	"indirizzo": "VIA DEL GIACINTO,37",
	"lon": "11.3040099",
	"lat": "44.51174572",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DRUSIANI EX RIZZO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 2",
	"indirizzo": "VIA GIOVANNI SEGANTINI",
	"lon": "11.30396943",
	"lat": "44.50351366",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "RENO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "ZANOTTI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 2",
	"indirizzo": "VIA DEL GIACINTO,39",
	"lon": "11.30359329",
	"lat": "44.51175413",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CARDUCCI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 20",
	"indirizzo": "VIA DANTE ALIGHIERI,3",
	"lon": "11.35462637",
	"lat": "44.48692678",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "FORTUZZI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 20",
	"indirizzo": "VIALE STENIO POLISCHI",
	"lon": "11.3501643",
	"lat": "44.48360608",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "ROLANDINO DA PASSEGGERI  E PEPOLI (Presidenza)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 20",
	"indirizzo": "VIA GIOVANNI PASCOLI,5",
	"lon": "11.35027698",
	"lat": "44.4855725",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "DON MILANI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 21",
	"indirizzo": "LARGO CARDINALE GIACOMO LERCARO,10",
	"lon": "11.37281313",
	"lat": "44.47979168",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "MARCONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 21",
	"indirizzo": "VIA LAURA BASSI VERATTI,22",
	"lon": "11.36794052",
	"lat": "44.48269134",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "MARCONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 21",
	"indirizzo": "VIA LAURA BASSI VERATTI,22",
	"lon": "11.36794052",
	"lat": "44.48269134",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SANTO STEFANO",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "PEPOLI  (sede distaccata)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 21",
	"indirizzo": "LARGO CARDINALE GIACOMO LERCARO",
	"lon": "11.37188036",
	"lat": "44.47941892",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "BOTTEGO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 3",
	"indirizzo": "VIA DELLA BEVERARA,158",
	"lon": "11.33045113",
	"lat": "44.52051438",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "COOP. AZZURRA STATALE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 3",
	"indirizzo": "VIA DELLA BEVERARA,188",
	"lon": "11.33066385",
	"lat": "44.5224153",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "SALVO D'ACQUISTO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 3",
	"indirizzo": "VIA DELLA BEVERARA,188",
	"lon": "11.33066385",
	"lat": "44.5224153",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "SILVANI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 3",
	"indirizzo": "VIA DELLA SELVA PESCAROLA,29",
	"lon": "11.32446342",
	"lat": "44.52483596",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GIROTONDO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 4",
	"indirizzo": "VIA RAFFAELE PETTAZZONI,1",
	"lon": "11.3564261",
	"lat": "44.54241204",
	"nome": "Girotondo",
	"tipo": "infanzia",
	"stud": "52",
	"non_freq": "36",
	"stranieri": "34",
	"freq": "16"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "L. MARSILI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 4",
	"indirizzo": "VIA SANT'ANNA,4",
	"lon": "11.35552917",
	"lat": "44.54869159",
	"nome": "Marsini",
	"tipo": "primaria",
	"stud": "123",
	"non_freq": "23",
	"stranieri": "29",
	"freq": "100"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "PANZINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 4",
	"indirizzo": "VIA GIULIO VERNE,19",
	"lon": "11.36136256",
	"lat": "44.54543629",
	"nome": "Panzini",
	"tipo": "media",
	"stud": "234",
	"non_freq": "54",
	"stranieri": "64",
	"freq": "180"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "VILLA TORCHI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 4",
	"indirizzo": "VIA GIULIO VERNE,21",
	"lon": "11.36192552",
	"lat": "44.54566987",
	"nome": "Villa Torchi",
	"tipo": "primaria",
	"stud": "255",
	"non_freq": "73",
	"stranieri": "69",
	"freq": "182"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ACRI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA CLELIA BARBIERI,5",
	"lon": "11.27734473",
	"lat": "44.50175699",
	"nome": "Acri",
	"tipo": "primaria",
	"stud": "238",
	"non_freq": "102",
	"stranieri": "99",
	"freq": "136"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "FEDERZONI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA ANTONIO DI VINCENZO,11",
	"lon": "11.34465791",
	"lat": "44.50783946",
	"nome": "Federzoni",
	"tipo": "infanzia",
	"stud": "75",
	"non_freq": "47",
	"stranieri": "55",
	"freq": "28"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "FEDERZONI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA ANTONIO DI VINCENZO,11",
	"lon": "11.34465791",
	"lat": "44.50783946",
	"nome": "Federzoni",
	"tipo": "primaria",
	"stud": "228",
	"non_freq": "113",
	"stranieri": "137",
	"freq": "115"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "LA GIOSTRA (NUOVA MATERNA IN VIA F.BARBIERI)",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA GIOVANNI FRANCESCO BARBIERI,5/A",
	"lon": "11.34679656",
	"lat": "44.51689315",
	"nome": "La Giostra",
	"tipo": "infanzia",
	"stud": "47",
	"non_freq": "27",
	"stranieri": "40",
	"freq": "20"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "NUOVA GROSSO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA CRISTOFORO DA BOLOGNA,29",
	"lon": "11.3384707",
	"lat": "44.51928974",
	"nome": "Grosso",
	"tipo": "primaria",
	"stud": "237",
	"non_freq": "79",
	"stranieri": "57",
	"freq": "158"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "NUOVA SCUOLA INFANZIA NAVILE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA CRISTOFORO DA BOLOGNA,27/5",
	"lon": "11.33861722",
	"lat": "44.51995147",
	"nome": "Nuova Navile",
	"tipo": "infanzia",
	"stud": "50",
	"non_freq": "22",
	"stranieri": "26",
	"freq": "28"
}, {
	"Quartiere": "NAVILE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "TESTONI - FIORAVANTI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 5",
	"indirizzo": "VIA ANTONIO DI VINCENZO,55",
	"lon": "11.34551193",
	"lat": "44.51284876",
	"nome": "Testoni Fioravanti",
	"tipo": "media",
	"stud": "340",
	"non_freq": "136",
	"stranieri": "150",
	"freq": "204"
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CLINICA NEUROLOGICA INFANTILE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA UGO FOSCOLO,7",
	"lon": "11.33019899",
	"lat": "44.49203747",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "CLINICA PEDIATRICA GOZZADINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA GIUSEPPE MASSARENTI,11",
	"lon": "11.36173673",
	"lat": "44.49251653",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "CLINICA PEDIATRICA GOZZADINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA GIUSEPPE MASSARENTI,11",
	"lon": "11.36173673",
	"lat": "44.49251653",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "ERCOLANI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "MURA DI PORTA GALLIERA,1",
	"lon": "11.34979972",
	"lat": "44.50293187",
	"nome": "Ercolani",
	"tipo": "primaria",
	"stud": "176",
	"non_freq": "50",
	"stranieri": "",
	"freq": "126"
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "GIORDANI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA LIBIA,57",
	"lon": "11.36595018",
	"lat": "44.49607203",
	"nome": "Giordani",
	"tipo": "infanzia",
	"stud": "100",
	"non_freq": "35",
	"stranieri": "",
	"freq": "65"
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "GIORDANI PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA MARIO MUSOLESI,22",
	"lon": "11.36631421",
	"lat": "44.49561589",
	"nome": "Giordani",
	"tipo": "primaria",
	"stud": "149",
	"non_freq": "62",
	"stranieri": "",
	"freq": "87"
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "IRNERIO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 6",
	"indirizzo": "VIA ANGELO FINELLI,2",
	"lon": "11.34906357",
	"lat": "44.50235529",
	"nome": "Irnerio",
	"tipo": "media",
	"stud": "379",
	"non_freq": "175",
	"stranieri": "",
	"freq": "204"
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "J. DELLA QUERCIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 7",
	"indirizzo": "VIA SCANDELLARA,54/3",
	"lon": "11.38454076",
	"lat": "44.49748195",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "LIVIO TEMPESTA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 7",
	"indirizzo": "VIA TOMMASO MARTELLI,37",
	"lon": "11.39873267",
	"lat": "44.49072677",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "SCANDELLARA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 7",
	"indirizzo": "VIA SCANDELLARA,54/5",
	"lon": "11.38474329",
	"lat": "44.49790516",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "SCANDELLARA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 7",
	"indirizzo": "VIA SCANDELLARA,54/5",
	"lon": "11.38474329",
	"lat": "44.49790516",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAN VITALE",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "VILLETTA MATTEI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 7",
	"indirizzo": "VIA ENRICO MATTEI,20",
	"lon": "11.39937348",
	"lat": "44.49486693",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "A. AVOGLI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA SARAGOZZA,238",
	"lon": "11.31196621",
	"lat": "44.48876513",
	"nome": "Armandi Avogli",
	"tipo": "primaria",
	"stud": "119",
	"non_freq": "25",
	"stranieri": "",
	"freq": "94"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "BOMBICCI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA FILIPPO TURATI,84",
	"lon": "11.32183888",
	"lat": "44.49131061",
	"nome": "Bombicci",
	"tipo": "primaria",
	"stud": "253",
	"non_freq": "79",
	"stranieri": "",
	"freq": "174"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "CARRACCI SUCC.",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA CA' SELVATICA,11",
	"lon": "11.33322867",
	"lat": "44.49280795",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "GUINIZELLI SEDE",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA CA' SELVATICA,11",
	"lon": "11.33322867",
	"lat": "44.49280795",
	"nome": "Gunizelli",
	"tipo": "media",
	"stud": "481",
	"non_freq": "211",
	"stranieri": "",
	"freq": "270"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "MANZOLINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA SANT'ISAIA,20",
	"lon": "11.33373209",
	"lat": "44.49363921",
	"nome": "Manzolini",
	"tipo": "infanzia",
	"stud": "50",
	"non_freq": "15",
	"stranieri": "",
	"freq": "35"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "MANZOLINI",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA SANT'ISAIA,20",
	"lon": "11.33373209",
	"lat": "44.49363921",
	"nome": "Manzolini (primaria)",
	"tipo": "primaria",
	"stud": "230",
	"non_freq": "72",
	"stranieri": "",
	"freq": "158"
}, {
	"Quartiere": "SARAGOZZA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "XXI APRILE PRIMARIA",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 8",
	"indirizzo": "VIA 21 APRILE 1945,24",
	"lon": "11.31501571",
	"lat": "44.49188074",
	"nome": "XXI Aprile",
	"tipo": "primaria",
	"stud": "274",
	"non_freq": "93",
	"stranieri": "",
	"freq": "181"
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA SECONDARIA DI PRIMO GRADO",
	"Struttura": "IL GUERCINO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 9",
	"indirizzo": "VIA LUIGI LONGO,4",
	"lon": "11.385633",
	"lat": "44.46771765",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA DELL'INFANZIA",
	"Struttura": "SANZIO RAFFAELLO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 9",
	"indirizzo": "VIA GIUSEPPE CESARE ABBA,7",
	"lon": "11.37815231",
	"lat": "44.46469765",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}, {
	"Quartiere": "SAVENA",
	"Servizio": "SCUOLA PRIMARIA",
	"Struttura": "SANZIO RAFFAELLO",
	"Tipo struttura": "Statale",
	"Istituzione scol": "ISTITUTO COMPRENSIVO N. 9",
	"indirizzo": "VIA GIUSEPPE CESARE ABBA,7",
	"lon": "11.37815231",
	"lat": "44.46469765",
	"nome": "",
	"tipo": "",
	"stud": "",
	"non_freq": "",
	"stranieri": "",
	"freq": ""
}];
